---
title: "Central Limit Theorem"
author: "Russell Almond"
date: "September 8, 2020"
format:
  html:
    sidebar: id-intro
---

Pick a distribution:
* Uniform -- platykurtic
* Binomial -- symmetric and mesokurtic
* Exponential -- highly skewed
* Gamma (shape = 3) -- skewed
* T (df =3) -- high kurtosis

Slide the sample size up and down, notice how the empirical distribution function and histogram coverge to the normal distribution function and density.

```{=html}
<iframe width="100%" height="500" src="../apps/CentralLimitTheorem.R"></iframe>
```



The left column shows the original distribution.  (I call that the _black hat_ in my CLT demo.)

The right column shows the distribution of means of size $M$ (adjusted with the second slider).  (This is the _white hat_ distribuiton, and $M$ is the number of cards averaged to get the white hat value.)  

The top row shows histograms with a normal curve on top.

The bottom row shows a QQ-plot.  This shows how much the sample is different from a normal distribution.  A normal distribution should be right on top of the diagonal line.  

* A U-shaped curve indicates skewness (and an upside down U is negatively skewed).  Try the exponential distribution.

* An S-shaped curve indicates high kurtosis (a backwards S, low kurtosis)  Try the Student-t and Uniform distributions.

As $M$ (the number of cards averages to get to the white hat) gets bigger, the distribution should get closer and closer to the normal distribution.

## Take home

* Even if the underlying data aren't normal, the distribuiton of the means of various groups should be close to normal.

* Close depends on the sample size.

* A bigger sample is needed if the data are highly skewed (expontential and gamma) or leptokurtic (exponential and Student t).
