---
title: "Scatterplot examples"
format: 
  html:
    sidebar: id-intro
---


# Linear Relationships

All three of these example are indications that linear regression is a
reasonable to way to summarize the relationship between $X$ and $Y$.


## Mostly linear

This happens when we have a moderately high to strong correlation.

```{=html}
<iframe width="100%" height="500" src="../apps/CorrelationExamples1.R"></iframe>
```


## Blobby Elipse

As the correlation coefficient gets lower, the scatterplot looks more
blobby, but you can still tell that there is a slope.  This is a weak
to moderate correlation.

```{=html}
<iframe width="100%" height="500" src="../apps/CorrelationExamples2.R"></iframe>
```

## No Relationship

Not much is going on here.  One thing that confuses people is the idea
that linear regression doesn't work here.  Actually, it gives a quite
accurate picture: it tells you that not much is going on, which is
what is actually happening.  The prediction from the regression will
be that $\bar Y$ is the best predicted value for $Y$.


```{=html}
<iframe width="100%" height="500" src="../apps/CorrelationExamples3.R"></iframe>
```

# Signs that the linear model doesn't work.

The challenge to using regression (and correlation) to summarize the
relationship between $X$ and $Y$ is when the relationship is
non-linear.  Here the correlation/regression will tell about the
linear part of the relationship, but missing the non-linear part.  If
the non-linear part is small, this might not be too bad.  But if it is
big, then _linear_ regression could be misleading.  (There are various
types of non-linear regression that are covered in more advanced
classes).


## Curve

A curved relationship doesn't look like a line.  

Consider a quadradic relationship:
$$ Y = b_2 X^2 + b_1 X + b_0 + \epsilon$$

This is a multiple (or quadradic) regression.  You can adjust the
coefficients in the plot below.

```{=html}
<iframe width="100%" height="500" src="../apps/CorrelationExamples4.R"></iframe>
```

If we try to run a _linear_ regression when the relationship is
curved, it will only tell us part of the story.  The story it will
tell is the red line, and not the blue curve.

## Broken Lines

Sometimes the reltionship changes somewhere through the range of the
data.  Often this is a ceiling effect: the effect of $X$ on $Y$ hits a
ceiling.  For example, in the first couple of years of teaching, the
ability of new teachers rises very rapidly as they gain experience.
But after 3--5 years, the effect levels out and the teachers grow much
more slowly.

Ideally we would fit two linear regression to these data splitting at a certain value of $X$, $x_0$.  So,

$$ Y = \begin{cases}
 b_{11} X + b_{01} + \epsilon & \text {when} X \leq x_0 \\
 b_{12} X + b_{02} + \epsilon & \text {when} X \ge x_0
 \end{cases}
 $$
 
```{=html}
<iframe width="100%" height="500" src="../apps/CorrelationExamples5.R"></iframe>
```

Check out [this page](CorrelationExercise.qmd) to practice identifying these.
