---
title: "Kurtosis Practice using Quantile-Quantile Plots"
author: "Russell Almond"
date: "February 23, 2019"
format: 
  html:
    sidebar: id-intro
---


## Kurtosis Determination Exercise.

In this exercise, the computer will generate 3 datasets: X, Y and Z.
These will be randomly assigned to high (leptokurtic), medium
(mesokurtic) and low (platykurtic) distributions.

The data (sorted in order) are plotted on the Y axis and the quantiles
of a standard normal (qnorm) distribution are plotted on the X axis.
A normal distribution should appear as a straight line; leptokurtic
and platykurtic distributions as 'S' or 'Z' curves. (A 'U' or 'C'
shaped curve indicates skewness, not kurtosis.)  _Note: SPSS plots the
normal quantiles on the Y axis and the data on the X: Which means that
leptokurtic and platykurtic distributions will curve in the opposite
direction from these Q-Q plots._


You can redraw from the same distributions by changing the sample size
(higher sample sizes are easier to see).

```{=html}
<iframe width="100%" height="500" src="../apps/KurtosisQQ.R"></iframe>
```

To try again with different distributions, reload the page.  If you
are having trouble, try increasing the sample size: sometimes a small
sample won't display the characteristics of the distribution strongly.

Here are the other exercises in this series:

* Skewness Practice:
   + [Histograms](SkewnessPractice.qmd)
   + [Boxplots](SkewnessBoxplot.qmd)
   + [Q-Q Plots](SkewnessQQ.qmd)

* Kurtosis Practice:
   + [Histograms](KurtosisPractice.qmd)
   + [Boxplots](KurtosisBoxplots.qmd)
   + [Q-Q Plots](KurtosisQQ.qmd)






