---
title: "Kurtosis Practice"
author: "Russell Almond"
date: "February 23, 2019"
format: 
  html:
    sidebar: id-intro
---


## Kurtosis Determination Exercise.

In this exercise, the computer will generate 3 datasets: X, Y and Z.
These will be randomly assigned to high (leptokurtic), medium
(mesokurtic) and low (platykurtic) distributions. A normal curve is
drawn over the top for reference.

```{=html}
<iframe width="100%" height="500" src="../apps/KurtosisPractice.R"></iframe>
```

You can redraw from the same distributions by changing the sample
size.  To try again with different distributions, reload the page.  If
you are having trouble, try increasing the sample size: sometimes a
small sample won't display the characteristics of the distribution
strongly.

Here are the other exercises in this series:

* Skewness Practice:
   + [Histograms](SkewnessPractice.qmd)
   + [Boxplots](SkewnessBoxplot.qmd)
   + [Q-Q Plots](SkewnessQQ.qmd)

* Kurtosis Practice:
   + [Histograms](KurtosisPractice.qmd)
   + [Boxplots](KurtosisBoxplots.qmd)
   + [Q-Q Plots](KurtosisQQ.qmd)





