---
title: "Normal Parameters"
author: "Russell Almond"
date: "January 24, 2019"
format: 
  html:
    sidebar: id-intro
---


A *parameter* is a value that can be changed in a statistical model.
For example, the *mean* and *standard deviation* are the parameters of
the [normal
distribution](https://en.wikipedia.org/wiki/Normal_distribution),
which is a model for a population.  Changing the value of a parameter,
changes the model. We can see that in the illustration below.  Try
changing the values of the mean and standard deviation and see what
happens to the shape of the curve.

## Inputs and Outputs

```{=html}
<iframe width="100%" height="500" src="../apps/NormalParams1.R"></iframe>
```

## Scale and Location Parameters

The *mean* has a special role in the normal distribution; it
determines where the center of the curve is.  This makes it a
*location parameter*.

The *standard deviation* has a special role in the normal
distribution; it stretches and shrinks the curve around the mean.
This makes it a *scale parameter*.

Sometimes, the effects of scale and location parameters can be hard to
see.  This is because most statistical graphics packages adjust the
axis of the graph, so that the curve will always appear centered in
the plotting window.  In the normal curve above, I fixed the plotting
window so that you can see the curve move.  In the example below, I
let the plotting window adjust with the curve.  Notice how the curve
stays the same, but the labels on the axis change.

```{=html}
<iframe width="100%" height="500" src="../apps/NormalParams1.R"></iframe>
```




