---
title: "Skewness Practice with Quantile-Quantile Plots"
author: "Russell Almond"
date: "February 23, 2019"
format: 
  html:
    sidebar: id-intro
---


## Skewness Determination Exercise.

In this exercise, the computer will generate 3 datasets: A, B and C.
These will be randomly assigned to a positively skewed, negatively
skewed, and symmetric distribution type. The data (sorted in order)
are plotted on the Y axis and the quantiles of a standard normal
(qnorm) distribution are plotted on the X axis.  A normal distribution
should appear as a straight line; positively skewed distributions will
yield a 'U' shaped curve, and negatively skewed distributions a 'C'
shaped curve.  (An 'S' or 'Z' shaped curve indicates kurtosis, not
skewness).  _Note: SPSS plots the normal quantiles on the Y axis and
the data on the X: Which means that leptokurtic and platykurtic
distributions will curve in the opposite direction from these Q-Q
plots._


You can redraw from the same distributions by changing the sample
size. (Bigger sample sizes are easier.)

```{=html}
<iframe width="100%" height="500" src="../apps/SkewnessQQ.R"></iframe>
```


To try again with different distributions, reload the page.  If you
are having trouble, try increasing the sample size: sometimes a small
sample won't display the characteristics of the distribution strongly.

Here are the other exercises in this series:

* Skewness Practice:
   + [Histograms](SkewnessPractice.qmd)
   + [Boxplots](SkewnessBoxplot.qmd)
   + [Q-Q Plots](SkewnessQQ.qmd)

* Kurtosis Practice:
   + [Histograms](KurtosisPractice.qmd)
   + [Boxplots](KurtosisBoxplots.qmd)
   + [Q-Q Plots](KurtosisQQ.qmd)






