---
title: "Skewness Boxplot Practice"
author: "Russell Almond"
date: "February 23, 2019"
format: 
  html:
    sidebar: id-intro
---


## Skewness Determination Exercise.

In this exercise, the computer will generate 3 datasets:  A, B and C.  These will be randomly assigned to a positively skewed, negatively skewed, and symmetric distribution type.    Your job is to determine which is which.

You can redraw from the same distributions by changing the sample size.

```{=html}
<iframe width="100%" height="500" src="../apps/SkewnessBoxplot.R"></iframe>
```

To try again with different distributions, reload the page.  If you
are having trouble, try increasing the sample size: sometimes a small
sample won't display the characteristics of the distribution strongly.

## What to look for:

* Is the box from median to quartile longer on one side than the other?
* Is the whisker longer on one side than the other?
* Are there outliers on one side and not the other?

All three of these are signs of skewness in that direction (longer
box, whisker, or outliers).

## Related Pages

Here are the other exercises in this series:

* Skewness Practice:
   + [Histograms](SkewnessPractice.qmd)
   + [Boxplots](SkewnessBoxplot.qmd)
   + [Q-Q Plots](SkewnessQQ.qmd)

* Kurtosis Practice:
   + [Histograms](KurtosisPractice.qmd)
   + [Boxplots](KurtosisBoxplots.qmd)
   + [Q-Q Plots](KurtosisQQ.qmd)






