---
title: "Standard Deviations"
author: "Russell Almond"
date: "1/29/2019"
format: 
  html:
    sidebar: id-intro
server: shiny
---

```{r}
#| context: setup
#| include: false
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
```


```{r}
data <- rnorm(15,mean=0,sd=2)
plot(data,1:length(data))
abline(v=0)
segments(mean(data),1:length(data),data,1:length(data))
sd(data)
hist(data)
```
$$ \sqrt(\sum (X_i - \mu)^2/N) $$

```{r}
data1 <- c(11,13,14,15,17,18,19,20)
data2 <- c(12,15,15,15,15,15,15,15)
data3 <- c(5,13,19,24,33,38,51,70)
data4 <- c(11,12,13,16,18,20,22,23)
par(mfrow=c(2,2))
plot(data1,1:length(data1),main="Data 1",xlim=c(0,50))
abline(v=mean(data1))
segments(mean(data1),1:length(data1),data1,1:length(data1))
sd(data1)
plot(data2,1:length(data2),main="Data 2",xlim=c(0,50))
abline(v=mean(data2))
segments(mean(data2),1:length(data2),data2,1:length(data2))
sd(data2)
plot(data3,1:length(data3),main="Data 3",xlim=c(0,50))
abline(v=mean(data3))
segments(mean(data3),1:length(data3),data3,1:length(data3))
sd(data3)
plot(data4,1:length(data4),main="Data 4",xlim=c(0,50))
abline(v=mean(data4))
segments(mean(data4),1:length(data4),data4,1:length(data4))
sd(data4)
```


